services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  api:
    build: ./cgapi
    container_name: cgapi
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/controlgastos
volumes:
  mongo_data:
