services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    container_name: cgapi
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development # Options: 'development', 'production'
      - PORT=8080 # The port your server will listen on
      - HOST=localhost # Hostname for the server
      - CORS_ORIGIN=http://localhost:* # Allowed CORS origin, adjust as necessary
      - COMMON_RATE_LIMIT_WINDOW_MS=1000 # Window size for rate limiting (ms)
      - COMMON_RATE_LIMIT_MAX_REQUESTS=20 # Max number of requests per window per IP
      - MONGO_URL=mongodb://mongo:27017/controlgastos
volumes:
  mongo_data:
